name: Bug report
description: Reporta un bug
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe el problema
    validations:
      required: true
